version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: quay.io/vektorcloud/cibase:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker build -t base .
      - deploy: 
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              docker tag base quay.io/vektorcloud/base:latest
            else
              docker tag base quay.io/vektorcloud/base:${CIRCLE_BRANCH}
            fi
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
            docker push quay.io/vektorcloud/base
