version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: quay.io/vektorcloud/cibase:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: docker build -t base .
      - deploy: 
          command: |
            docker tag base quay.io/vektorcloud/base:$(grep FROM Dockerfile  | cut -f2 -d\:)
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
            docker push quay.io/vektorcloud/base
